# server properties
server:
  port: 8081

# Secret Key To Generate Token
app:
  secretKey: '[@q2Xg7@T4mOplFu#Ae]'
  jwtValidityMinutes: 15
  
    
# Configure Database here
#datasource:
#  url: jdbc:h2:mem:sai
#  username: sa
#  password: 
#  driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: false

########
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/employeedb?useSSL=false
#    username: root
#    password: Kishore199806@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#  main:
#    allow-circular-references: true

######
spring:
  datasource:
    url: jdbc:mysql://digitaldb.cjk2meko415e.us-east-1.rds.amazonaws.com:3306/a2bdigitaldb?useSSL=true
    username: root
    password: Kishore199806
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  main:
    allow-circular-references: true

    
#spring:
#  main:
#    allow-circular-references: true

# Error Messages
jwtUtil:
  expiredMessage: Token has been expired
  malformedMessage: Token is in invalid format
  signatureMessage: Token signature is invalid
  nullOrEmptyMessage: Token is either null or empty
  unsupportedMessage: Claims for token is not supported
  
userDetails:
  errorMessage: Incorrect Username or Password
  badCredentialsMessage: Incorrect Username or Password
  disabledAccountMessage: Your account has been disabled
  lockedAccountMessage: You account has been locked, please contact your administrator for more details